# Generated by Django 5.2.10 on 2026-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(help_text='Inquiry notifications will be sent here', max_length=254)),
                ('send_email_on_inquiry', models.BooleanField(default=True, help_text='Toggle email notifications on/off')),
                ('email_subject_prefix', models.CharField(default='[SUTPLY] New Inquiry', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('Residential', 'Residential Project'), ('Commercial', 'Commercial Project'), ('Designer', 'Interior Designer / Architect'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='form', help_text='form or popup', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quote Inquiry',
                'verbose_name_plural': 'Quote Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
